Updated Gradle, fixed some formatting
For some reason, Kotlin compiler *itself* is crashing.

CompilationException: Back-end (JVM) Internal error: Couldn't inline method call: CALL 'public final fun single <T> (a: mpd.com.common.collect.valuecollections.ValueIntAdapter<T of mpd.com.common.collect.valuecollections.ValueCollectionsKt.single>, <this>: mpd.com.common.collect.valuecollections.VIntCollection<T of mpd.com.common.collect.valuecollections.ValueCollectionsKt.single>, predicate: kotlin.Function1<T of mpd.com.common.collect.valuecollections.ValueCollectionsKt.single, kotlin.Boolean>): T of mpd.com.common.collect.valuecollections.ValueCollectionsKt.single [inline] declared in mpd.com.common.collect.valuecollections.ValueCollectionsKt' type=T of mpd.com.common.collect.valuecollections.ValueCollectionsKt.single origin=null
Method: single (Lmpd/com/common/collect/valuecollections/ValueIntAdapter;Lmpd/com/common/collect/valuecollections/VIntCollection;Lkotlin/jvm/functions/Function1;)Ljava/lang/Object;:
Caused By: AnalyzerException: Error at instruction #2 ARETURN: Cannot pop operand off an empty stack.